/*global systemDictionary:true */
'use strict';

systemDictionary = {
  'gsmsms adapter settings': {
    'en': 'Adapter settings for gsmsms',
    'de': 'Adaptereinstellungen für gsmsms',
    'ru': 'Настройки адаптера для gsmsms',
    'pt': 'Configurações do adaptador para gsmsms',
    'nl': 'Adapterinstellingen voor gsmsms',
    'fr': "Paramètres d'adaptateur pour gsmsms",
    'it': "Impostazioni dell'adattatore per gsmsms",
    'es': 'Ajustes del adaptador para gsmsms',
    'pl': 'Ustawienia adaptera dla gsmsms',
    'zh-cn': 'gsmsms的适配器设置'
  },
  "basic": {
    "en": "Basic settings",
    "de": "Grundeinstellungen",
    "ru": "Основные настройки",
    "pt": "Configurações básicas",
    "nl": "Basis instellingen",
    "fr": "Paramètres de base",
    "it": "Impostazioni di base",
    "es": "Ajustes básicos",
    "pl": "Podstawowe ustawienia",
    "zh-cn": "基本设置"
  },
  "gsm": {
    "en": "GSM",
    "de": "GSM",
    "ru": "GSM",
    "pt": "GSM",
    "nl": "GSM",
    "fr": "GSM",
    "it": "GSM",
    "es": "GSM",
    "pl": "GSM",
    "zh-cn": "全球通"
  },
  "serialport": {
    "en": "serial port",
    "de": "serielle Schnittstelle",
    "ru": "Серийный порт",
    "pt": "porta serial",
    "nl": "seriële poort",
    "fr": "port série",
    "it": "porta seriale",
    "es": "Puerto serial",
    "pl": "Port szeregowy",
    "zh-cn": "串行端口"
  },
  "portConnection": {
    "en": "Port- & connection settings",
    "de": "Port- & Verbindungseinstellungen",
    "ru": "Настройки порта и подключения",
    "pt": "Configurações de porta e conexão",
    "nl": "Poort- & verbindingsinstellingen",
    "fr": "Paramètres de port et de connexion",
    "it": "Impostazioni di porta e connessione",
    "es": "Configuración de puerto y conexión",
    "pl": "Ustawienia portu i połączenia",
    "zh-cn": "端口和连接设置"
  },
  "port": {
    "en": "serial port (e.g. /dev/ttyUSB1)",
    "de": "serielle Schnittstelle (z.B. /dev/ttyUSB1)",
    "ru": "последовательный порт (например, /dev/ttyUSB1)",
    "pt": "porta serial (por exemplo, /dev /ttyUSB1)",
    "nl": "seriële poort (bijv. /dev/ttyUSB1)",
    "fr": "port série (par exemple /dev/ttyUSB1)",
    "it": "porta seriale (es. /dev/ttyUSB1)",
    "es": "puerto serie (por ejemplo, /dev/ttyUSB1)",
    "pl": "port szeregowy (np. /dev/ttyUSB1)",
    "zh-cn": "串口（例如 /dev/ttyUSB1）"
  },
  "pin": {
    "en": "PIN (if activated on SIM)",
    "de": "PIN (sofern auf SIM aktiviert)",
    "ru": "PIN-код (если активирован на SIM-карте)",
    "pt": "PIN (se ativado no SIM)",
    "nl": "PIN (indien geactiveerd op SIM)",
    "fr": "PIN (si activé sur SIM)",
    "it": "PIN (se attivato su SIM)",
    "es": "PIN (si está activado en SIM)",
    "pl": "PIN (jeśli aktywowany na karcie SIM)",
    "zh-cn": "PIN（如果在 SIM 卡上激活）"
  },
  "connectionMode": {
    "en": "Connection mode",
    "de": "Verbindungsmodus",
    "ru": "Режим подключения",
    "pt": "Modo de conexão",
    "nl": "Verbindingsmodus",
    "fr": "Mode de connexion",
    "it": "Modalità di connessione",
    "es": "Modo de conexión",
    "pl": "Tryb połączenia",
    "zh-cn": "连接方式"
  },
  "alwaysopen": {
    "en": "Allways open",
    "de": "Immer geöffnet",
    "ru": "Всегда открыт",
    "pt": "Sempre aberto",
    "nl": "Altijd open",
    "fr": "Toujours ouvert",
    "it": "Sempre aperto",
    "es": "Siempre abierto",
    "pl": "Zawsze otwarte",
    "zh-cn": "永远开放"
  },
  "polling": {
    "en": "Retrieval",
    "de": "Abruf",
    "ru": "Воспроизведение",
    "pt": "Recuperação",
    "nl": "Ophalen",
    "fr": "Récupération",
    "it": "Recupero",
    "es": "Recuperación",
    "pl": "Wyszukiwanie",
    "zh-cn": "恢复"
  },
  "sendonly": {
    "en": "Send only",
    "de": "Nur senden",
    "ru": "Только отправить",
    "pt": "Envie apenas",
    "nl": "Alleen verzenden",
    "fr": "Envoyer seulement",
    "it": "Invia solo",
    "es": "Solamente enviar",
    "pl": "Tylko wyślij",
    "zh-cn": "只发送"
  },
  "pollinginterval": {
    "en": "Retrieval interval (min)",
    "de": "Abrufintervall (min)",
    "ru": "Интервал поиска (мин)",
    "pt": "Intervalo de recuperação (min)",
    "nl": "Ophaalinterval (min)",
    "fr": "Intervalle de récupération (min)",
    "it": "Intervallo di recupero (min)",
    "es": "Intervalo de recuperación (min)",
    "pl": "Interwał wyszukiwania (min)",
    "zh-cn": "检索间隔（分钟）"
  },
  "gsmsettings": {
    "en": "GSM settings",
    "de": "GSM-Einstellungen",
    "ru": "Настройки GSM",
    "pt": "Configurações GSM",
    "nl": "GSM-instellingen",
    "fr": "Paramètres GSM",
    "it": "Impostazioni GSM",
    "es": "Configuraciones GSM",
    "pl": "Ustawienia GSM",
    "zh-cn": "GSM 设置"
  },
  "autoDeleteOnReceive": {
    "en": "Auto delete on recieve",
    "de": "Automatisches Löschen bei Empfang",
    "ru": "Автоматическое удаление при получении",
    "pt": "Apagar automaticamente ao receber",
    "nl": "Automatisch verwijderen bij ontvangst",
    "fr": "Suppression automatique à la réception",
    "it": "Eliminazione automatica alla ricezione",
    "es": "Eliminar automáticamente al recibir",
    "pl": "Automatyczne usuwanie przy odbiorze",
    "zh-cn": "收到后自动删除"
  },
  "enableConcatenation": {
    "en": "Enable concatenation",
    "de": "Verkettung aktivieren",
    "ru": "Включить конкатенацию",
    "pt": "Habilitar concatenação",
    "nl": "Aaneenschakeling inschakelen",
    "fr": "Activer la concaténation",
    "it": "Abilita concatenazione",
    "es": "Habilitar la concatenación",
    "pl": "Włącz konkatenację",
    "zh-cn": "启用串联"
  },
  "incomingCallIndication": {
    "en": "Incoming call indication",
    "de": "Anzeige eingehender Anrufe",
    "ru": "Индикация входящего звонка",
    "pt": "Indicação de chamada de entrada",
    "nl": "Inkomende oproep indicatie",
    "fr": "Indication d'appel entrant",
    "it": "Indicazione chiamata in arrivo",
    "es": "Indicación de llamada entrante",
    "pl": "Wskazanie połączenia przychodzącego",
    "zh-cn": "来电显示"
  },
  "incomingSMSIndication": {
    "en": "Incoming SMS indication",
    "de": "Anzeige eingehender SMS",
    "ru": "Индикация входящего SMS",
    "pt": "Indicação de entrada de SMS",
    "nl": "Inkomende SMS indicatie",
    "fr": "Indication SMS entrant",
    "it": "Indicazione SMS in arrivo",
    "es": "Indicación de SMS entrantes",
    "pl": "Wskazanie przychodzącej wiadomości SMS",
    "zh-cn": "来电短信指示"
  },
  "customInitCommand": {
    "en": "Custom Iinit command",
    "de": "Benutzerdefinierter Iinit-Befehl",
    "ru": "Пользовательская команда Iinit",
    "pt": "Comando Iinit personalizado",
    "nl": "Aangepast Iinit-commando",
    "fr": "Commande Iinit personnalisée",
    "it": "Comando di inizializzazione personalizzato",
    "es": "Comando Iinit personalizado",
    "pl": "Niestandardowe polecenie Iinit",
    "zh-cn": "自定义 Iinit 命令"
  },
  "cnmiModemOpen": {
    "en": "CNMI when modem open",
    "de": "CNMI bei geöffnetem Modem",
    "ru": "CNMI при открытом модеме",
    "pt": "CNMI quando o modem abre",
    "nl": "CNMI wanneer modem open is",
    "fr": "CNMI à l'ouverture du modem",
    "it": "CNMI quando il modem è aperto",
    "es": "CNMI cuando el módem está abierto",
    "pl": "CNMI, gdy modem jest otwarty",
    "zh-cn": "调制解调器打开时的 CNMI"
  },
  "cnmiModemClosed": {
    "en": "CNMI when modem closed",
    "de": "CNMI bei geschlossenem Modem",
    "ru": "CNMI при закрытом модеме",
    "pt": "CNMI quando o modem está fechado",
    "nl": "CNMI wanneer modem gesloten is",
    "fr": "CNMI à la fermeture du modem",
    "it": "CNMI quando il modem è chiuso",
    "es": "CNMI cuando el módem está cerrado",
    "pl": "CNMI po zamknięciu modemu",
    "zh-cn": "调制解调器关闭时的 CNMI"
  },
  "serialportsettings": {
    "en": "Serial port setttings",
    "de": "Einstellungen für den seriellen Anschluss",
    "ru": "Настройки последовательного порта",
    "pt": "Configurações de porta serial",
    "nl": "Instellingen seriële poort",
    "fr": "Paramètres du port série",
    "it": "Impostazioni della porta seriale",
    "es": "Configuración del puerto serie",
    "pl": "Ustawienia portu szeregowego",
    "zh-cn": "串口设置"
  },
  "baudRate": {
    "en": "Baud rate",
    "de": "Baudrate",
    "ru": "Скорость передачи",
    "pt": "Taxa de transmissão",
    "nl": "baudrate",
    "fr": "Débit en bauds",
    "it": "Velocità di trasmissione",
    "es": "Tasa de baudios",
    "pl": "Szybkość transmisji",
    "zh-cn": "波特率"
  },
  "dataBits": {
    "en": "databits",
    "de": "Daten Bits",
    "ru": "данные",
    "pt": "bits de dados",
    "nl": "databits",
    "fr": "Bits de données",
    "it": "bit di dati",
    "es": "bits de datos",
    "pl": "bity danych",
    "zh-cn": "数据位"
  },
  "stopBits": {
    "en": "stopbits",
    "de": "Stopp-Bits",
    "ru": "стоп-биты",
    "pt": "paradas",
    "nl": "stopbits",
    "fr": "bits d'arrêt",
    "it": "stopbits",
    "es": "bits de parada",
    "pl": "stopbity",
    "zh-cn": "停止位"
  },
  "parity": {
    "en": "parity",
    "de": "Parität",
    "ru": "паритет",
    "pt": "paridade",
    "nl": "pariteit",
    "fr": "parité",
    "it": "parità",
    "es": "paridad",
    "pl": "parytet",
    "zh-cn": "平价"
  },
  "none": {
    "en": "none",
    "de": "none",
    "ru": "none",
    "pt": "none",
    "nl": "none",
    "fr": "none",
    "it": "none",
    "es": "none",
    "pl": "none",
    "zh-cn": "none"
  },
  "odd": {
    "en": "odd",
    "de": "odd",
    "ru": "odd",
    "pt": "odd",
    "nl": "odd",
    "fr": "odd",
    "it": "odd",
    "es": "odd",
    "pl": "odd",
    "zh-cn": "odd"
  },
  "even": {
    "en": "even",
    "de": "even",
    "ru": "even",
    "pt": "even",
    "nl": "even",
    "fr": "even",
    "it": "even",
    "es": "even",
    "pl": "even",
    "zh-cn": "even"
  },
  "mark": {
    "en": "mark",
    "de": "mark",
    "ru": "mark",
    "pt": "mark",
    "nl": "mark",
    "fr": "mark",
    "it": "mark",
    "es": "mark",
    "pl": "mark",
    "zh-cn": "mark"
  },
  "space": {
    "en": "space",
    "de": "space",
    "ru": "space",
    "pt": "space",
    "nl": "space",
    "fr": "space",
    "it": "space",
    "es": "space",
    "pl": "space",
    "zh-cn": "space"
  },
  "rtscts": {
    "en": "RTS/CTS",
    "de": "RTS/CTS",
    "ru": "RTS / CTS",
    "pt": "RTS / CTS",
    "nl": "RTS/CTS",
    "fr": "RTS/CTS",
    "it": "RTS/CTS",
    "es": "RTS / CTS",
    "pl": "RTS/CTS",
    "zh-cn": "RTS/CTS"
  },
  "xon": {
    "en": "xon",
    "de": "xon",
    "ru": "xon",
    "pt": "xon",
    "nl": "xon",
    "fr": "xon",
    "it": "xon",
    "es": "xon",
    "pl": "xon",
    "zh-cn": "xon"
  },
  "xoff": {
    "en": "xoff",
    "de": "xoff",
    "ru": "xoff",
    "pt": "xoff",
    "nl": "xoff",
    "fr": "xoff",
    "it": "xoff",
    "es": "xoff",
    "pl": "xoff",
    "zh-cn": "xoff"
  },
  "xany": {
    "en": "xany",
    "de": "xany",
    "ru": "xany",
    "pt": "xany",
    "nl": "xany",
    "fr": "xany",
    "it": "xany",
    "es": "xany",
    "pl": "xany",
    "zh-cn": "仙妮"
  }
};
